name: 'sync with upstream'
inputs:
  upstream-repository:
    required: true
  upstream-branch:
    required: true
  downstream-branch:
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.upstream-repository }}
    - ${{ inputs.upstream-branch }}
    - ${{ inputs.downstream-branch }}
