name: Cleanup old branches
on:
  workflow_call:
    inputs:
      date:
        description: "A git-log compatible date format"
        default: '3 months ago'
        type: string
      dry_run:
        description: "Run in dry-run mode so no branches are deleted"
        default: true
        type: boolean
      branch_regex:
        description: "A regex for branches to include."
        default: '.*'
        type: string
      excluded_branches:
        description: "A comma seperated list of branch(es) to exclude"
        default: "main,master,develop"
        type: string
      excluded_branch_regex:
        description: "A regex for branches to exclude."
        default: ''
        type: string
      exclude_open_pr_branches:
        description: "Exclude branches that have an open pull request"
        default: true
        type: boolean

jobs:
  housekeeping:
    name: Cleanup old branches
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Run delete-old-branches-action
        #
        # Instead of specifying the local path like
        # `./delete-old-branches` here we must specify the full
        # path. This is because if we use reuse this workflow in
        # another repository the relative path is assumed to be
        # relative to that repository instead of relative to this
        # repository that actually contains the workflow and the
        # action.
        #
        # Eventually it should be possible to determine the repository
        # from which the workflow came and then use that to set the
        # path (`github.workflow_ref` as described in
        # https://docs.github.com/en/actions/learn-github-actions/contexts)
        # but that doesn't seem possible yet.
        #
        uses: delphix/actions/delete-old-branches@master
        with:
          repo_token: ${{ github.token }}
          date: ${{ inputs.date }}
          dry_run: ${{ inputs.dry_run }}
          branch_regex: ${{ inputs.branch_regex }}
          excluded_branches: ${{ inputs.excluded_branches }}
          excluded_branch_regex: ${{ inputs.excluded_branch_regex }}
          exclude_open_pr_branches: ${{ inputs.exclude_open_pr_branches }}
