name: Cleanup old branches
"on":
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"  # Weekly
jobs:
  delete-old-branches:
    uses: ./.github/workflows/delete-old-branches-workflow.yaml
    permissions:
      contents: write
      pull-requests: read
    with:
      dry_run: false
